# Generated by Django 3.2.9 on 2021-12-16 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forms',
            options={'verbose_name': 'Formulario', 'verbose_name_plural': 'Formularios'},
        ),
    ]
