version: "3"
services:
    hackaton_backend:
        container_name: hackaton_backend
        build:
            context: .
            dockerfile: .docker/Dockerfile
        environment:
            - DEBUG=1
            - PYTHONUNBUFFERED=1
            - DJANGO_SETTINGS_MODULE=hackaton.settings.base
        command: sh -c "python manage.py migrate && gunicorn hackaton.wsgi -b 0.0.0.0:8000 --reload"
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - postgres_hackaton
    postgres_hackaton:
        container_name: postgres_hackaton
        image: postgres
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres