version: "3.9"

services:
    hackaton_backend:
        container_name: hackaton_backend
        build:
            context: .
            dockerfile: .docker/Dockerfile
        command: /bin/bash
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - postgres_hackaton
            - pgadmin_hackaton
        
    postgres_hackaton:
        container_name: postgres_hackaton
        image: postgres
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    pgadmin_hackaton:
        container_name: pgadmin_hackaton
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        volumes:
            - ./pgadmin_data:/data
        ports:
            - 5050:80

    testdb_hackaton:
        image: postgres
        environment:
            - POSTGRES_DB=testdb_hackaton
            - POSTGRES_USER=testdb_hackaton
            - POSTGRES_PASSWORD=testdb_hackaton
        ports:
            - 5432:5436

volumes:
    postgres_data: {}
    pgadmin_data: {}