# Generated by Django 3.2.9 on 2021-12-16 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0003_auto_20211216_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Banco', 'verbose_name_plural': 'Bancos'},
        ),
        migrations.AlterModelOptions(
            name='compensationbox',
            options={'verbose_name': 'Caja de Compensación', 'verbose_name_plural': 'Cajas de Compensación'},
        ),
        migrations.AlterModelOptions(
            name='mutual',
            options={'verbose_name': 'Mutual', 'verbose_name_plural': 'Mutuales'},
        ),
    ]
