# Generated by Django 3.2.9 on 2021-12-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_country_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="comuna",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
