# Generated by Django 3.2.9 on 2021-12-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20211215_1424'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comuna',
            table='comuna',
        ),
    ]
