#!/usr/bin/env bash
set -euo pipefail

_usage() {
  echo "developing"
  echo "    up                  start the server in development mode"
  echo "    test                run test suites"
  echo ""
  echo "requirements"
  echo "    pipi                install python requirements based on requirements.txt"
  echo ""
  echo "migrations"
  echo "    migrate             run pending migrations"
  echo "    makemig             make django migrations"
  echo ""
  echo "tools"
  echo "    black               run black"
  echo "    isort               run isort"
  echo "    createapp           create django app"
  echo "    createsuperuser     create superadmin"
  exit 1
}

# show usage if no argument is given
arg=${1:-}
shift || _usage

case ${arg} in
up|run|server|runserver)
  python manage.py runserver 0.0.0.0:8000
;;
test)
  pytest "$@" --isort --black
;;
cov)
  pytest "$@" --isort --black --cov=hackaton
;;
black)
  black .
;;
isort)
  isort .
;;
createapp)
  mkdir ./hackaton/apps/"$@" &&
  python manage.py startapp "$@" ./hackaton/apps/"$@"
;;
createsuperuser)
  python manage.py createsuperuser
;;
pipi)
  pip install -r requirements.txt
;;
migrate)
  python manage.py migrate "$@"
;;
makemigrations|makemigration|makemig)
  python manage.py makemigrations "$@"
;;
*)
  _usage
;;
esac
