# Generated by Django 3.2.9 on 2021-12-15 18:50

from django.db import migrations

from hackaton.apps.business.models import CompanyType, Gratification, PaymentMobilization
from hackaton.apps.locations.models import Country

def init(apps, schema_editor):
    country_code = "CL"
    country = Country.objects.filter(code=country_code).first()
    payment_mobilization = [
        {"code": "fija", "name": "Fija a todo evento"},
        {"code": "vacaciones", "name": "Descuenta vacaciones y ausentismo"},
        {"code": "licencias", "name": "Descuenta solo licencias"},
    ]
    
    gratification = [
        {"code": "M", "name": "Mensual"},
        {"code": "A", "name": "Anual"},
    ]
    
    company_type = [
        {"code": "privada", "name": "Empresa Privada"},
        {"code": "sin-lucro", "name": "Empresa Sin Fines de Lucro"},
        {"code": "particular", "name": "Casa Particular"},
        {"code": "audiovisual", "name": "Empresa Audiovisual"},
    ]
    create(PaymentMobilization, payment_mobilization, country)
    create(Gratification, gratification, country)
    create(CompanyType, company_type, country)


def create(objeto, items, country):
    for item in items:
        obj = objeto.objects.filter(code=item.get("code")).first()
        if not obj:
            obj = objeto()
            obj.code = item.get("code")
            obj.name=item.get("name")
            obj.country=country
        else:
            obj.name = item.get("name")
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [migrations.RunPython(init)]
