# Generated by Django 3.2.9 on 2021-12-16 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20211215_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingaccount',
            options={'verbose_name': 'Cuenta Contable', 'verbose_name_plural': 'Cuentas Contables'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Compañia', 'verbose_name_plural': 'Compañias'},
        ),
        migrations.AlterModelOptions(
            name='companytype',
            options={'verbose_name': 'Tipo de Compañia', 'verbose_name_plural': 'Tipos de Compañias'},
        ),
        migrations.AlterModelOptions(
            name='costcenter',
            options={'verbose_name': 'Centro de Costo', 'verbose_name_plural': 'Centros de Costos'},
        ),
        migrations.AlterModelOptions(
            name='gratification',
            options={'verbose_name': 'Pago Gratificación', 'verbose_name_plural': 'Pagos Gratificación'},
        ),
        migrations.AlterModelOptions(
            name='paymentmobilization',
            options={'verbose_name': 'Pago Movilización y Colación', 'verbose_name_plural': 'Pagos Movilización'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AlterModelOptions(
            name='unions',
            options={'verbose_name': 'Sindicato', 'verbose_name_plural': 'Sindicatos'},
        ),
    ]
