# Generated by Django 3.2.9 on 2021-12-17 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0004_auto_20211216_0104'),
        ('forms', '0002_alter_forms_options'),
        ('locations', '0003_auto_20211215_1546'),
        ('business', '0003_auto_20211216_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='billing_rut',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_direction',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_giro',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='checking_bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='central.bank'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.forms'),
        ),
        migrations.AlterField(
            model_name='company',
            name='gratification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='business.gratification'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mutual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='central.mutual'),
        ),
        migrations.AlterField(
            model_name='company',
            name='payment_mobilization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='business.paymentmobilization'),
        ),
        migrations.AlterField(
            model_name='company',
            name='representative_email',
            field=models.EmailField(db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='representative_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='representative_rut',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='business.companytype'),
        ),
    ]
